import React, { useState } from 'react';
import { CheckSquare, Copy, Download, Check, HelpCircle, UserCheck, CreditCard, Building2 } from 'lucide-react';

export default function QuestionChecklist({ checklist }) {
  const [checkedState, setCheckedState] = useState({});
  const [copied, setCopied] = useState(false);

  if (!checklist || !checklist.categories) return null;

  const { summaryTip, categories } = checklist;

  const toggleCheck = (catIdx, qIdx) => {
    const key = `${catIdx}-${qIdx}`;
    setCheckedState(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const formatAsPlainText = () => {
    let text = `CONSENTIA PATIENT PREPARATION CHECKLIST\n`;
    text += `=======================================\n\n`;
    if (summaryTip) text += `TIP: ${summaryTip}\n\n`;

    categories.forEach(cat => {
      text += `[ ${cat.title} ]\n`;
      cat.questions.forEach((q, qIdx) => {
        const isChecked = checkedState[`${categories.indexOf(cat)}-${qIdx}`];
        text += `  ${isChecked ? '[X]' : '[ ]'} ${q}\n`;
      });
      text += `\n`;
    });

    text += `---\nGenerated by Consentia Patient Navigator (Educational Preparation Tool)\n`;
    return text;
  };

  const handleCopy = () => {
    const text = formatAsPlainText();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const text = formatAsPlainText();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `consentia-patient-checklist-${new Date().toISOString().slice(0,10)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getTargetIcon = (target) => {
    const lower = (target || '').toLowerCase();
    if (lower.includes('doctor') || lower.includes('care')) return <UserCheck className="w-4 h-4 text-sage-600" />;
    if (lower.includes('billing') || lower.includes('hospital')) return <Building2 className="w-4 h-4 text-clay-600" />;
    return <CreditCard className="w-4 h-4 text-amber-600" />;
  };

  return (
    <div className="space-y-6">
      
      {/* Header & Copy / Download Toolbar */}
      <div className="bg-paper-50 p-6 rounded-2xl border border-paper-300/60 shadow-xs space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-paper-200 pb-4">
          <div className="flex items-center gap-2.5">
            <CheckSquare className="w-6 h-6 text-clay-500" />
            <div>
              <h3 className="text-xl font-bold font-serif text-slate-900">
                Personalized Question Checklist
              </h3>
              <p className="text-xs text-slate-600">
                Actionable questions to ask before signing consent forms or paying bills
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-xl text-slate-700 bg-paper-100 hover:bg-paper-200 border border-paper-300/60 transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-sage-600" /> : <Copy className="w-3.5 h-3.5 text-clay-600" />}
              {copied ? 'Copied to Clipboard!' : 'Copy Checklist'}
            </button>

            <button
              type="button"
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-xl text-paper-50 bg-clay-500 hover:bg-clay-600 shadow-xs transition-all"
            >
              <Download className="w-3.5 h-3.5" /> Download (.txt)
            </button>
          </div>
        </div>

        {/* Practical Tip Callout */}
        {summaryTip && (
          <div className="bg-clay-50/60 p-3.5 rounded-xl border border-clay-500/20 text-xs text-clay-900 flex items-start gap-2">
            <HelpCircle className="w-4 h-4 text-clay-600 shrink-0 mt-0.5" />
            <p><span className="font-bold">Preparation Tip:</span> {summaryTip}</p>
          </div>
        )}
      </div>

      {/* Categorized Question Lists */}
      <div className="space-y-5">
        {categories.map((cat, catIdx) => (
          <div 
            key={catIdx}
            className="bg-paper-50 p-5 rounded-2xl border border-paper-300/70 shadow-xs space-y-4"
          >
            <div className="flex items-center gap-2 border-b border-paper-200 pb-2.5">
              {getTargetIcon(cat.target)}
              <h4 className="text-base font-bold font-serif text-slate-900">
                {cat.title}
              </h4>
              <span className="ml-auto text-[11px] font-semibold text-slate-500 bg-paper-100 px-2 py-0.5 rounded border border-paper-300/40">
                {cat.questions.length} Questions
              </span>
            </div>

            <div className="space-y-2.5">
              {cat.questions.map((q, qIdx) => {
                const isChecked = !!checkedState[`${catIdx}-${qIdx}`];

                return (
                  <div 
                    key={qIdx}
                    onClick={() => toggleCheck(catIdx, qIdx)}
                    className={`flex items-start gap-3 p-3.5 rounded-xl border transition-all cursor-pointer ${
                      isChecked 
                        ? 'bg-sage-50/80 border-sage-300 text-slate-500 line-through' 
                        : 'bg-paper-50 border-paper-300/60 hover:border-clay-500/40 hover:bg-paper-100/60 text-slate-800'
                    }`}
                  >
                    <input 
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => {}} // Handled by parent div
                      className="mt-1 h-4 w-4 rounded border-paper-300 text-clay-600 focus:ring-clay-500 shrink-0 cursor-pointer"
                    />
                    <span className="text-sm leading-relaxed font-sans select-none">
                      {q}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
